on:
  push:
    branches:
      - main # Replace with your desired branch name

name: npm build, lint, test, and publish

jobs:
  build-and-publish:
    name: Build and Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14 # Replace with the desired Node.js version


      - name: Build Docker image
        run: docker build -t pavan4593/github-action-example-node .

      - name: Log in to Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker push pavan4593/github-action-example-node
